### ISSUE TITLE
PCI Coral Edge TPU not detected

### ISSUE THREAD

**Issue by vavallee-wp** [blakeblackshear/blakeshome-charts#47]
Hi! I am trying to get this chart to work with my pci coral, but no luck. I have the latest frigate chart

The coral is micro pci, installed in a pcie card. I have installed the card in my kubernetes node and followed the install drivers documentation from google.

When I run frigate, I get the below error.

Relevant settings in values.yaml

coral:
  enabled: true
  hostPath: /dev/apex_0

detectors:
     coral:
       type: edgetpu
       device: pci`

2023-07-06 19:53:27.470818310  Process detector:coral:                                                                                                                                            │
│ 2023-07-06 19:53:27.473297980  Traceback (most recent call last):                                                                                                                                 │
│ 2023-07-06 19:53:27.473590561    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate                                                                  │
│ 2023-07-06 19:53:27.473597680      delegate = Delegate(library, options)                                                                                                                          │
│ 2023-07-06 19:53:27.473602945    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__                                                                       │
│ 2023-07-06 19:53:27.473614135      raise ValueError(capture.message)                                                                                                                              │
│ 2023-07-06 19:53:27.473618595  ValueError                                                                                                                                                         │
│ 2023-07-06 19:53:27.473622310                                                                                                                                                                     │
│ 2023-07-06 19:53:27.473659310  During handling of the above exception, another exception occurred:                                                                                                │
│ 2023-07-06 19:53:27.473664406                                                                                                                                                                     │
│ 2023-07-06 19:53:27.473668344  Traceback (most recent call last):                                                                                                                                 │
│ 2023-07-06 19:53:27.473674492    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap                                                                                    │
│ 2023-07-06 19:53:27.473678554      self.run()                                                                                                                                                     │
│ 2023-07-06 19:53:27.473683098    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run                                                                                           │
│ 2023-07-06 19:53:27.473722094      self._target(*self._args, **self._kwargs)                                                                                                                      │
│ 2023-07-06 19:53:27.473726767    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector                                                                                        │
│ 2023-07-06 19:53:27.473731828      object_detector = LocalObjectDetector(detector_config=detector_config)                                                                                         │
│ 2023-07-06 19:53:27.473736295    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__                                                                                            │
│ 2023-07-06 19:53:27.473761224      self.detect_api = create_detector(detector_config)                                                                                                             │
│ 2023-07-06 19:53:27.473765963    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector                                                                                   │
│ 2023-07-06 19:53:27.473770182      return api(detector_config)                                                                                                                                    │
│ 2023-07-06 19:53:27.473774886    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__                                                                               │
│ 2023-07-06 19:53:27.473779430      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)                                                                                          │
│ 2023-07-06 19:53:27.473806995    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate                                                                  │
│ 2023-07-06 19:53:27.473811588      raise ValueError('Failed to load delegate from {}\n{}'.format(                                                                                                 │
│ 2023-07-06 19:53:27.473815829  ValueError: Failed to load delegate from libedgetpu.so.1.0

**Comment by vavallee-wp** [comment]
This seems to have been a hardware issue (BIOS??)
I moved the coral from a Dell SFF to an IBM and it detects and works perfectly.
My guess is there were some security settings in BIOS that I wasn't able to find.
